name: GitHub Actions Demo
run-name: ${{ github.actor }} is starting deployment 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: cd / && cd ~/cv-about && sh ./deployment/npm_run.sh
